### ISSUE TITLE
python-flask container example not compatible with AAD express settings

### ISSUE THREAD

**Issue by anders-kiaer** [microsoft/python-sample-vscode-flask-tutorial#17]
Thanks for the `python-sample-vscode-flask-tutorial`. Successfully followed the tutorial, and also deployment of the resulting container (following e.g. [Deploy Python using Docker containers](https://code.visualstudio.com/docs/python/tutorial-deploy-containers)).

**Observed behaviour:**

The example Azure web app for containers works as expected when [AAD with express settings](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad?toc=%2fazure%2fapp-service%2fcontainers%2ftoc.json#a-nameexpress-aconfigure-with-express-settings) is _not_ enabled in the app. When AAD express is turned on, the app is correctly redirecting to login (https://login.microsoftonline.com) when not authenticated, but when redirected back after successful login, the app returns `HTTP ERROR 500`.

**Expected behaviour:**

The Azure `python-sample-vscode-flask-tutorial` container example works with express settings in App service AAD enabled, or the `README.md` contains references/information regarding changes needed for express web app AD service settings to work.

**How to reproduce:**

* Download this example repository.
* Upload and build corresponding container using Azure Container Registry.
* Create an "Azure Web app for Containers", and link it to the container. Add the `WEBSITES_PORT=5000` application settings as described in the [Dockerfile](https://github.com/Microsoft/python-sample-vscode-flask-tutorial/blob/4fc1bc5cb35715baac58177271e04493f947c4a3/Dockerfile#L8).
* The app works as expected at this step.
* Turn on basic Azure App Service Authentication / Authorization (e.g. using Azure AD) using Express settings.
* Unauthenticated users are now still as expected redirected to login for authentication, however on redirect back to the app the server now returns `HTTP ERROR 500`.

**Comment by kraigb** [comment]
Thanks for the report; it's good to know about the behavior, which we'll have to look into.

**Comment by kraigb** [comment]
@JoshuaPartlow One for you to look into with the Flask tutorial.

**Comment by HansKallekleiv** [comment]
Is there any update on this issue? I'm getting the same results as @anders-kiaer, except for the last part.
In my case turning on authentication (using Azure AD) does not appear to do anything at all. 

We want to host quite a few web apps on Azure, but the lack of AD authentication is preventing us from doing so.

**Comment by qubitron** [comment]
I have gotten this working using Azure Web Apps (without containers), @HansKallekleiv initially it didn't appear to be working until I set the following setting:
![image](https://user-images.githubusercontent.com/17804393/60319224-95a7f780-992a-11e9-8cf5-c81e08732f62.png)

I also needed to open the site in an InPrivate session to see the login screen, I think my main browser may have been logged into active directory already.

@anders-kiaer I will take a look at the web apps for containers flavor next.

**Comment by HansKallekleiv** [comment]
Thanks for looking into this @qubitron 
I'm also using containers, and have tried adding that action without success.
Using anonymous session does not help.

These screenshots might be relevant:
![1](https://user-images.githubusercontent.com/16436291/60334543-0804f000-999c-11e9-94cd-a19820ca422f.PNG)

![2](https://user-images.githubusercontent.com/16436291/60334556-13f0b200-999c-11e9-9f42-9efe18ccf303.png)

There is a warning/information that 

*To enable Authentication / Authorization, please ensure all your custom domains have corresponding SSL bindings, your .NET version is configured to “4.5” or higher and manage pipeline mode is set to “Integrated”* , 

but I'm not sure that is relevant? There are no custom domains atleast.

**Comment by qubitron** [comment]
I was able to reproduce the issue in containers, and our team has found a workaround, 

There is known issue with easyauth (middleware) where in some cases, the request header length gets larger than 4096 and the request fails. The mitigation is to set this app setting ```WEBSITE_AUTH_DISABLE_IDENTITY_FLOW``` to ```true```, can you try that and let us know if it works?

More information on this setting is [here](https://github.com/cgillum/easyauth/wiki/Advanced-Application-Settings).

**Comment by anders-kiaer** [comment]
@qubitron Thanks! 🙇 The provided workaround `WEBSITE_AUTH_DISABLE_IDENTITY_FLOW = true` worked, tried it some weeks ago for the first time. Tried again now - and now it appears to work also without that application setting. Perhaps the underlying issue has been fixed? 🎉👷 

_**A follow up question regarding Azure web app service + the 🐳  Docker flavor:**_

For **Single Container** (screenshot below) authentication now works out of the box. However, selecting the **Docker Compose** functionality and a minimal configuration setup (using the same image as when doing **Single container**), authentication suddenly is bypassed (i.e. you go directly to the app). 
```yaml
version: '3'
services:
  web:
    image: someregistry.azurecr.io/someimage:latest
    ports:
      - 80:5000
```
Tried both with and without the `ports` setting. Are you able to reproduce? Is there something that should be changed/added in the 🐳 Docker compose configuration snippet above?

![image](https://user-images.githubusercontent.com/31612826/64252961-8346cd00-cf1c-11e9-9162-7224d9aac2f1.png)

_cc: @HansKallekleiv_

**Comment by VladyslavHnatchenko** [comment]
Hi all! Sorry @anders-kiaer, @qubitron please can you explain where you add WEBSITE_AUTH_DISABLE_IDENTITY_FLOW = true; in your code (in app.py or in Dockerfile or ...?)
Thank you for your answer.

**Comment by anders-kiaer** [comment]
I added it the same place as `WEBSITES_PORT=5000`, i.e. under _Configuration_ in the Azure web app.

Having said that, I have recently created new web apps (using Docker containers), and today it is working without the workaround for my part, so to me it looks like the underlying bug is fixed.

**Comment by anders-kiaer** [comment]
> For Single Container (screenshot below) authentication now works out of the box. However, selecting the Docker Compose functionality and a minimal configuration setup (using the same image as when doing Single container), authentication suddenly is bypassed (i.e. you go directly to the app).

After I posted this comment, this has now been "fixed" by greying out the _Authentication / Authorization_ tab when you use Docker compose, with a tooltip saying that "This feature is not supported with multi-container apps". 

I.e. at least indicating that it is not working with Docker compose, even though technically it does not need to be a multi-container app. E.g. this will still not work:
```yaml
version: '3'
services:
  web:
    image: some_acr.azurecr.io/pythonflasktutorial:latest
    ports:
      - 80:5000
```

**Comment by VladyslavHnatchenko** [comment]
@anders-kiaer, thank you very much for your answer! I added here in the Configuration -> Application settings -> WEBSITE_AUTH_DISABLE_IDENTITY_FLOW = true; but it's fixed my problem. When I turn off Authentication/Authorization(Log in with Azure Active Directory), my flask app worked correct, but when I turn on this function, I have 500 error(without details), in the last step of my workflow in the app. Thank you!

**Comment by VladyslavHnatchenko** [comment]
Sorry @anders-kiaer, why you add WEBSITES_PORT=5000 this, I don't add this?

**Comment by anders-kiaer** [comment]
Based on this line: https://github.com/microsoft/python-sample-vscode-flask-tutorial/blob/3b80224983662fc115dbe4f21c3e22ae5a433dec/Dockerfile#L6-L11
