### ISSUE TITLE
Specify Browser - Firefox & flask

### ISSUE THREAD

**Issue by MortalCatalyst** [microsoft/python-sample-vscode-flask-tutorial#19]
How can I define the browser to launch with?

from this I am using.

```json
{
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "microblog"                
            },
            "args": [
                "run",
                "--no-debugger",
                // "--no-reload"      // Remove to auto-reload modified pages
            ]
        },
```
If I want to use firefox or the forefox extension for vscode as my default development browser how do I add it to the launch configuration?

Specifically this extension.
https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug

Which has as its launch code

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch localhost",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost/index.html",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
``

However I cannot seem to get both flask and firefox together in the same debug configuration.

**Comment by ucheNkadiCode** [comment]
@haniamr -> Is there an easy way to solve this? It doesn't seem as though this is an issue with the sample itself.

**Comment by kraigb** [comment]
This is not an issue with the sample and would be better raised on the VS Code repo directly. https://github.com/microsoft/vscode/issues
