### ISSUE TITLE
TypeError: required field "type_ignores" missing from Module when using werkzeug 0.15.3

### ISSUE THREAD

**Issue by halderex** [microsoft/python-sample-vscode-flask-tutorial#27]
File "C:\Repository\python-sample-vscode-flask-tutorial\.env\lib\site-packages\werkzeug\routing.py", line 945, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module

Updating requirements.txt resolves the issue:
Werkzeug==0.15.5

**Comment by kraigb** [comment]
Thanks. MayI suggest you create a PR with the fix, so you get the contribution history?

**Comment by halderex** [comment]
> Thanks. MayI suggest you create a PR with the fix, so you get the contribution history?

Sure! Created PR #29
